# This is a basic workflow to help you get started with Actions

tabname: Build

on:
  pull_request:
    branches: ["main"]

escjobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          tabnode-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: CI=false npm run build
      # - run: npm test
